spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8089
server.servlet.context-path=/
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

pathupload=/resources/static/import/

spring.resources.cache.period=0

spring.devtools.restart.enabled=true


